apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-weight": "-2"
    "helm.sh/hook-delete-policy": "hook-succeeded"
  labels:
    app: {{ .Values.name }}
    giantswarm.io/service-type: "managed"
data:
  config.yaml: |
    service:
      delete:
        resources:
          resourceFile: "/var/run/{{ .Values.name }}/configmap/resources.json"
      kubernetes:
        address: ''
        inCluster: true
        tls:
          caFile: ''
          crtFile: ''
          keyFile: ''
  resources.json: |
    [
        {
            "kind": "Service",
            "name": "coredns",
            "namespace": "kube-system",
            "matchLabels": {
                "k8s-app": "coredns"
            },
            "excludeLabels": {
                "giantswarm.io/service-type": "managed"
            }
        },
        {
            "kind": "Deployment",
            "name": "coredns",
            "namespace": "kube-system",
            "matchLabels": {
                "k8s-app": "coredns"
            },
            "excludeLabels": {
                "giantswarm.io/service-type": "managed"
            }
        },
        {
            "kind": "ConfigMap",
            "name": "coredns",
            "namespace": "kube-system",
            "excludeLabels": {
                "giantswarm.io/service-type": "managed"
            }
        },
        {
            "kind": "ClusterRoleBinding",
            "name": "system:coredns",
            "excludeLabels": {
                "giantswarm.io/service-type": "managed"
            }
        },
        {
            "kind": "ClusterRole",
            "name": "system:coredns",
            "excludeLabels": {
                "giantswarm.io/service-type": "managed"
            }
        },
        {
            "kind": "ServiceAccount",
            "name": "coredns",
            "namespace": "kube-system",
            "excludeLabels": {
                "giantswarm.io/service-type": "managed"
            }
        }
    ]
