apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  labels:
    giantswarm.io/service-type: "{{ .Values.serviceType }}"
    k8s-app: {{ .Values.name }}
    kubernetes.io/name: "CoreDNS"
data:
  Corefile: |
    .:{{ .Values.ports.dns.port }} {
        cache {{ .Values.configmap.cache }}
        errors
        health
        kubernetes {{ .Values.cluster.kubernetes.domain }} {{ .Values.cluster.kubernetes.API.clusterIPRange }} {{ .Values.cluster.calico.CIDR }} {
          fallthrough in-addr.arpa ip6.arpa
          pods insecure
          upstream
        }
        log . {
          class denial
          class error
        }
        loadbalance {{ .Values.loadbalancePolicy }}
        prometheus :{{ .Values.ports.prometheus }}

        {{- if .Values.configmap.proxy }}
        {{- range (.Values.configmap.proxy | trimAll "\n " |  split "\n") }}
        proxy {{ . }}
        {{- end }}
        {{- end }}
        proxy . /etc/resolv.conf
    }
