apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  labels:
    giantswarm.io/service-type: "{{ .Values.serviceType }}"
    k8s-app: {{ .Values.name }}
    kubernetes.io/name: "CoreDNS"
data:
  Corefile: |
    .:{{ .Values.ports.dns.port }} {
        {{- if not (contains "cache" .Values.configmap.custom) }}
        cache {{ .Values.configmap.cache }}
        {{- end }}
        errors
        health
        kubernetes {{ .Values.cluster.kubernetes.domain }} {{ .Values.cluster.kubernetes.API.clusterIPRange }} {{ .Values.cluster.calico.CIDR }} {
          fallthrough in-addr.arpa ip6.arpa
          pods insecure
          upstream
        }
        log . {
          class denial
          class error
        }
        loadbalance {{ .Values.loadbalancePolicy }}
        prometheus :{{ .Values.ports.prometheus }}

        {{- if .Values.configmap.forward }}
        forward . {{ range (.Values.configmap.forward | trimAll "\n " |  split "\n") }}{{ . }}{{ end }} /etc/resolv.conf {
          policy sequential
        }
        {{- else }}
        forward . /etc/resolv.conf
        {{- end }}

        reload
        autopath @kubernetes
    }

    {{- if .Values.configmap.custom }}
    {{- range (.Values.configmap.custom | trimAll "\n " |  split "\n") }}
    {{ . }}
    {{- end }}
    {{- end }}
