apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  labels:
    giantswarm.io/service-type: "{{ .Values.serviceType }}"
    k8s-app: {{ .Values.name }}
    kubernetes.io/name: "CoreDNS"
data:
  Corefile: |
    .:{{ .Values.ports.dns.targetPort }} {
        {{- if not (contains "cache" .Values.configmap.custom) }}
        cache {{ .Values.configmap.cache }}
        {{- end }}
        errors
        health
        kubernetes {{ .Values.cluster.kubernetes.domain }} {{ .Values.cluster.kubernetes.API.clusterIPRange }} {{ .Values.cluster.calico.CIDR }} {
          fallthrough in-addr.arpa ip6.arpa
          pods verified
          upstream
        }
        log . {
          {{- range (.Values.configmap.log | trimAll "\n " |  split "\n") }}
          class {{ . }}
          {{- end }}
        }
        loadbalance {{ .Values.loadbalancePolicy }}
        prometheus :{{ .Values.ports.prometheus }}

        {{- if .Values.configmap.forward }}
        forward . {{ range (.Values.configmap.forward | trimAll "\n " |  splitList "\n") }}{{ . }} {{ end }}/etc/resolv.conf {
          policy sequential
        }
        {{- else }}
        forward . /etc/resolv.conf
        {{- end }}

        reload
        autopath @kubernetes
    }

    {{- if .Values.configmap.custom }}
    {{- range (.Values.configmap.custom | trimAll "\n " |  splitList "\n") }}
    {{ . }}
    {{- end }}
    {{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: node-local-dns
  namespace: kube-system
  labels:
    addonmanager.kubernetes.io/mode: Reconcile
data:
  Corefile: |
    .:{{ .Values.ports.dns.targetPort }} {
        cache {
          success 9984 30
          denial 9984 5
        }
        errors
        reload
        loop
        forward . {{ .Values.cluster.kubernetes.DNS.IP }} {
                force_tcp
        }
        prometheus :{{ .Values.ports.prometheus }}
        health
    }