apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ .Values.name }}-local-dns
  namespace: kube-system
  labels:
    k8s-app: {{ .Values.name }}-local-dns
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
spec:
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 10%
  selector:
    matchLabels:
      k8s-app: {{ .Values.name }}-local-dns
  template:
    metadata:
       labels:
          k8s-app: {{ .Values.name }}-local-dns
    spec:
      priorityClassName: system-node-critical
      serviceAccountName: {{ .Values.name }}-local-dns
      hostNetwork: true
      dnsPolicy: Default  # Don't use cluster DNS.
      tolerations:
      - key: "CriticalAddonsOnly"
        operator: "Exists"
      containers:
      - name: {{ .Values.name }}-local-dns
        image: "k8s.gcr.io/k8s-dns-node-cache:1.15.3"
        resources:
          limits:
            memory: 30Mi
          requests:
            cpu: 25m
            memory: 5Mi
        args: [ "-localip", "$LOCAL_DNS_IP", "-conf", "/etc/coredns/Corefile","-dns.port", "1053"  ]
        env:        
        - name: LOCAL_DNS_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            add:
            - NET_BIND_SERVICE
            drop:
            - all
          readOnlyRootFilesystem: true
        ports:
        - containerPort: {{ .Values.ports.dns.targetPort }}
          name: {{ .Values.ports.dns.name }}-local-udp
          protocol: UDP
        - containerPort: {{ .Values.ports.dns.targetPort }}
          name: {{ .Values.ports.dns.name }}-local-tcp
          protocol: TCP
        livenessProbe:
          httpGet:
            host: localhost
            path: /health
            port: 8080
          initialDelaySeconds: 60
          timeoutSeconds: 5
        volumeMounts:
        - mountPath: /run/xtables.lock
          name: xtables-lock
          readOnly: false
        - name: config-volume
          mountPath: /etc/coredns
      volumes:
      - name: xtables-lock
        hostPath:
          path: /run/xtables.lock
          type: FileOrCreate
      - name: config-volume
        configMap:
          name: {{ .Values.name }}-local-dns
          items:
            - key: Corefile
              path: Corefile
