apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: coredns
spec:
  maxReplicas: {{ .Values.maxReplicas }}
  minReplicas: {{ .Values.minReplicas }}
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: coredns
  targetCPUUtilizationPercentage: 70
