apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  labels:
    giantswarm.io/service-type: "{{ .Values.serviceType }}"
    k8s-app: {{ .Values.name }}
    kubernetes.io/cluster-service: "true"
    kubernetes.io/name: "CoreDNS"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.name }}-local-dns
  namespace: {{ .Values.namespace }}
  labels:
    giantswarm.io/service-type: "{{ .Values.serviceType }}"
    k8s-app: {{ .Values.name }}-local-dns
    kubernetes.io/cluster-service: "true"
    kubernetes.io/name: "CoreDNS-local-dns"
